#!/usr/bin/env bash
set -euo pipefail

# Run preview and smoke POST as sudo. This script writes logs under ./run_logs.
# Usage: sudo bash scripts/run_preview_sudo.sh

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

mkdir -p run_logs

export DATABASE_URL='postgresql://devuser:devpass@localhost:5432/pembayaran_dev'

echo "[run] building..."
npm run build > run_logs/build_out.log 2>&1 || true

echo "[run] starting preview (background)..."
DATABASE_URL="$DATABASE_URL" npm run preview -- --port 5173 > run_logs/preview_out.log 2>&1 &
PREV_PID=$!
echo $PREV_PID > run_logs/preview.pid
echo "[run] preview pid=$PREV_PID"

# wait for preview to log the actual local URL (it may choose another port)
HOST='http://localhost:5173'
for i in {1..15}; do
	if grep -q "Local:" run_logs/preview_out.log 2>/dev/null; then
		# extract URL after 'Local:' (example: "  ➜  Local:   http://localhost:5174/")
		URL_LINE=$(grep "Local:" run_logs/preview_out.log | tail -n1)
		EXTRACTED=$(echo "$URL_LINE" | sed -n 's/.*Local:[[:space:]]*\(http[^ ]*\).*/\1/p')
		if [ -n "$EXTRACTED" ]; then
			# strip trailing slash
			HOST=$(echo "$EXTRACTED" | sed 's#/*$##')
			break
		fi
	fi
	sleep 1
done
echo "[run] using HOST=$HOST"

echo "[run] ensure admin password is known"
HASH=$(node -e "(async()=>{const b=await import('bcrypt'); const h=await b.hash('LocalTest123!',10); console.log(h)})()")
psql "$DATABASE_URL" -c "UPDATE users SET password_hash = '$HASH' WHERE username = 'admin';" >/dev/null 2>&1 || true
echo "[run] disable admin 2FA if enabled"
psql "$DATABASE_URL" -c "UPDATE users SET otp_2fa_enabled = false WHERE username = 'admin';" >/dev/null 2>&1 || true

echo "[run] create session_id for admin and write cookie jar"
SESSION_ID=$(node -e "console.log(require('crypto').randomUUID())")
# update DB
psql "$DATABASE_URL" -c "UPDATE users SET session_id = '$SESSION_ID' WHERE username = 'admin';" >/dev/null 2>&1 || true
# find admin id
ADMIN_ID=$(psql "$DATABASE_URL" -Atc "SELECT id FROM users WHERE username='admin' LIMIT 1;" 2>/dev/null || echo '')
EXPIRY=$(( $(date +%s) + 3600 ))
cat > run_logs/pemb_cookies.txt <<EOF
# Netscape HTTP Cookie File
# curl cookie jar generated by script
localhost	FALSE	/	FALSE	$EXPIRY	sessionid	{"userId":$ADMIN_ID,"sessionId":"$SESSION_ID"}
EOF


HOST="http://localhost:5173"

echo "[run] login as admin"
curl -s -c run_logs/pemb_cookies.txt -L -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Origin: $HOST" -H "Referer: $HOST/login" --data "username=admin&password=LocalTest123!" "$HOST/login?/login" -o run_logs/login_resp -w "%{http_code}"

echo "[run] selecting ids"
SANTRI_ID=$(psql "$DATABASE_URL" -Atc "SELECT id FROM santri LIMIT 1;")
TA_ID=$(psql "$DATABASE_URL" -Atc "SELECT id FROM tahun_ajaran WHERE is_active=true LIMIT 1;" )
if [ -z "$TA_ID" ]; then TA_ID=$(psql "$DATABASE_URL" -Atc "SELECT id FROM tahun_ajaran LIMIT 1;"); fi
JENIS_ID=$(psql "$DATABASE_URL" -Atc "SELECT id FROM jenis_pembayaran WHERE tipe LIKE '%sekali%' LIMIT 1;")
if [ -z "$JENIS_ID" ]; then psql "$DATABASE_URL" -c "INSERT INTO jenis_pembayaran (nama_pembayaran, tipe, nominal_default) VALUES ('TEMP Sekali Test','sekali',1000);"; JENIS_ID=$(psql "$DATABASE_URL" -Atc "SELECT id FROM jenis_pembayaran WHERE nama_pembayaran='TEMP Sekali Test' LIMIT 1;"); fi

echo "[run] using SANTRI_ID=$SANTRI_ID TA_ID=$TA_ID JENIS_ID=$JENIS_ID"

PAYLOAD="[{\"santriId\":$SANTRI_ID,\"tahunAjaranId\":$TA_ID,\"jenisPembayaranId\":$JENIS_ID,\"nominalDibayar\":1000}]"

echo "[run] POST create"
curl -s -b run_logs/pemb_cookies.txt -L -X POST -H "Origin: $HOST" -H "Referer: $HOST/transaksi/input" -F "paymentItemsJson=$PAYLOAD" $HOST/transaksi/input -o run_logs/input_post_response.json -w "%{http_code}"

echo "[run] show create response"
cat run_logs/input_post_response.json || true

echo "[run] show run_logs/trans_create_errors.log if exists"
if [ -f run_logs/trans_create_errors.log ]; then sed -n '1,240p' run_logs/trans_create_errors.log || true; else echo '<no file>'; fi

echo "[run] query system_logs"
node scripts/query_system_logs.js > run_logs/query_logs_out2.txt 2>&1 || true
sed -n '1,240p' run_logs/query_logs_out2.txt || true

echo "[run] latest pembayaran rows"
psql "$DATABASE_URL" -Atc "SELECT id,nomor_kwitansi,nominal_dibayar,tanggal_bayar FROM pembayaran ORDER BY id DESC LIMIT 10;"

echo "[run] tail preview log"
tail -n 200 run_logs/preview_out.log || true

echo "[run] done. preview pid=$PREV_PID (keep running)."
